from PyQt5 import QtCore, QtGui, QtWidgets
from MainWindow import *


class NewCandidateWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_open_main_window = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_main_window.setGeometry(QtCore.QRect(0, 440, 261, 50))
        self.btn_open_main_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_open_main_window.setStyleSheet("background-color: rgb(115, 199, 255);\n"
                                                "font: 18pt \"Times New Roman\";")
        self.btn_open_main_window.setAutoDefault(False)
        self.btn_open_main_window.setObjectName("btn_open_main_window")

        self.label_main_name = QtWidgets.QLabel(self.centralwidget)
        self.label_main_name.setGeometry(QtCore.QRect(0, 0, 1000, 40))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_main_name.setFont(font)
        self.label_main_name.setMouseTracking(False)
        self.label_main_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_name.setWordWrap(False)
        self.label_main_name.setObjectName("label_main_name")
        self.btn_save_profile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_profile.setGeometry(QtCore.QRect(590, 440, 400, 50))
        self.btn_save_profile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_save_profile.setStyleSheet("background-color: rgb(115, 199, 255);\n"
                                            "font: 18pt \"Times New Roman\";")
        self.btn_save_profile.setAutoDefault(False)
        self.btn_save_profile.setObjectName("btn_save_profile")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 981, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_fio = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_fio.setObjectName("plainTextEdit_fio")
        self.verticalLayout.addWidget(self.plainTextEdit_fio)
        self.comboBox_education = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_education.setObjectName("comboBox_education")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.verticalLayout.addWidget(self.comboBox_education)
        self.comboBox_work_experience = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_work_experience.setObjectName("comboBox_work_experience")
        self.comboBox_work_experience.addItem("")
        self.comboBox_work_experience.addItem("")
        self.comboBox_work_experience.addItem("")
        self.comboBox_work_experience.addItem("")
        self.comboBox_work_experience.addItem("")
        self.verticalLayout.addWidget(self.comboBox_work_experience)
        self.plainTextEdit_prof_skils = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_prof_skils.setObjectName("plainTextEdit_prof_skils")
        self.verticalLayout.addWidget(self.plainTextEdit_prof_skils)
        self.plainTextEdit_traning = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_traning.setObjectName("plainTextEdit_traning")
        self.verticalLayout.addWidget(self.plainTextEdit_traning)
        self.plainTextEdit_obsh_naych_work = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_obsh_naych_work.setObjectName("plainTextEdit_obsh_naych_work")
        self.verticalLayout.addWidget(self.plainTextEdit_obsh_naych_work)
        self.label_work_team = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_work_team.setObjectName("label_work_team")
        self.verticalLayout.addWidget(self.label_work_team)
        self.comboBox_work_team = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_work_team.setObjectName("comboBox_work_team")
        self.comboBox_work_team.addItem("")
        self.comboBox_work_team.addItem("")
        self.comboBox_work_team.addItem("")
        self.verticalLayout.addWidget(self.comboBox_work_team)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_open_main_window.setText(_translate("MainWindow", "Закрыть"))
        self.label_main_name.setText(_translate("MainWindow", "ИоНова - Центр Кадрового Развития"))
        self.btn_save_profile.setText(_translate("MainWindow", "Создать анкету"))
        self.plainTextEdit_fio.setPlainText(_translate("MainWindow", "ФИО"))
        self.comboBox_education.setItemText(0, _translate("MainWindow", "Аспирантура"))
        self.comboBox_education.setItemText(1, _translate("MainWindow", "Магистратура"))
        self.comboBox_education.setItemText(2, _translate("MainWindow", "Бакалавриат"))
        self.comboBox_education.setItemText(3, _translate("MainWindow", "СПО"))
        self.comboBox_education.setItemText(4, _translate("MainWindow", "Нет образования"))
        self.comboBox_work_experience.setItemText(0, _translate("MainWindow", "3 и более лет"))
        self.comboBox_work_experience.setItemText(1, _translate("MainWindow", "3 года"))
        self.comboBox_work_experience.setItemText(2, _translate("MainWindow", "2 года"))
        self.comboBox_work_experience.setItemText(3, _translate("MainWindow", "1 год"))
        self.comboBox_work_experience.setItemText(4, _translate("MainWindow", "нет опыта"))
        self.plainTextEdit_prof_skils.setPlainText(_translate("MainWindow", "Проф. навыки"))
        self.plainTextEdit_traning.setPlainText(_translate("MainWindow", "Повышение квалификации\n"
                                                                         ""))
        self.plainTextEdit_obsh_naych_work.setPlainText(
            _translate("MainWindow", "Участие в образов., науч., творческой деятельности\n"
                                     ""))
        self.label_work_team.setText(_translate("MainWindow", "Уровень работы в команде:"))
        self.comboBox_work_team.setItemText(0, _translate("MainWindow", "Высокий"))
        self.comboBox_work_team.setItemText(1, _translate("MainWindow", "Средний"))
        self.comboBox_work_team.setItemText(2, _translate("MainWindow", "Низкий"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    NewCandidateWin = QtWidgets.QMainWindow()
    ui = NewCandidateWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
